import LandingClient from '@/components/landing/LandingClient'

export const metadata = {
  title: 'MintyFit — Family Nutrition & Meal Planning',
  description:
    "MintyFit plans every meal around each family member's body — their age, weight, goals, and allergies. One plan. Everyone covered. Generated by AI in seconds.",
  openGraph: {
    title: 'MintyFit — Family Nutrition & Meal Planning',
    description:
      'Stop cooking two separate dinners. MintyFit calculates personalized portions for every family member from one recipe.',
    images: [{ url: '/MintyHero.webp', width: 1200, height: 630 }],
    type: 'website',
    siteName: 'MintyFit',
    url: 'https://mintyfit.com',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'MintyFit — Family Nutrition & Meal Planning',
    description: 'AI-powered nutrition planning for the whole family.',
    images: ['/MintyHero.webp'],
  },
  alternates: { canonical: 'https://mintyfit.com' },
}

const organizationJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  name: 'MintyFit',
  url: 'https://mintyfit.com',
  logo: 'https://mintyfit.com/favicon-192.png',
  description: 'The only nutrition platform built for families, not individuals.',
  foundingLocation: { '@type': 'Place', name: 'Estonia' },
  sameAs: [],
}

const websiteJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'MintyFit',
  url: 'https://mintyfit.com',
  description: 'AI-powered family nutrition and meal planning.',
  potentialAction: {
    '@type': 'SearchAction',
    target: 'https://mintyfit.com/recipes?q={search_term_string}',
    'query-input': 'required name=search_term_string',
  },
}

export default function Page() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteJsonLd) }} />
      <LandingClient />
    </>
  )
}
