-- recipe_ingredient_swaps — persisted ingredient swaps per user per recipe
-- Replaces local state so swaps survive page reloads and sync across sessions.

CREATE TABLE IF NOT EXISTS recipe_ingredient_swaps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  recipe_id UUID NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  original_name TEXT NOT NULL,
  replacement_name TEXT NOT NULL,
  replacement_note TEXT,
  amount_factor DOUBLE PRECISION DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(profile_id, recipe_id, original_name)
);

-- Index for fast lookup by user+recipe
CREATE INDEX IF NOT EXISTS idx_recipe_swaps_user_recipe
  ON recipe_ingredient_swaps(profile_id, recipe_id);

-- RLS: users can only manage their own swaps
ALTER TABLE recipe_ingredient_swaps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own swaps"
  ON recipe_ingredient_swaps
  FOR ALL
  TO authenticated
  USING (auth.uid() = profile_id)
  WITH CHECK (auth.uid() = profile_id);

-- Insert/update trigger for updated_at
CREATE OR REPLACE FUNCTION update_recipe_ingredient_swaps_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_recipe_ingredient_swaps_updated_at ON recipe_ingredient_swaps;
CREATE TRIGGER trg_recipe_ingredient_swaps_updated_at
  BEFORE UPDATE ON recipe_ingredient_swaps
  FOR EACH ROW EXECUTE FUNCTION update_recipe_ingredient_swaps_updated_at();
